### PR TITLE
Update installation.mdx

### PR DESCRIPTION
**Pull request by Jarak-Jakar**
Add a brief warning about differing line endings between Windows and Unix/Linux, and some short instructions about how you can try to address them.

### CODE REVIEW

**Comment by rohitpaulk** [comment]
> While git typically normalises the endings to and from the Unix style for you when you check code out and commit it back, your code editor probably by default adds new lines with the Windows style.

@Jarak-Jakar Trying to dig a bit deeper - wouldn't we expect this to fix the problem? i.e. Even if users have windows-style endings in their local directory, when the git push happens, they'd get normalized to unix-style. (assuming it's configured properly)

Maybe adding a `.gitattributes` file to all the starter repos would fix this? Could you try the following please: 

- Keep your editor on the windows-style endings setting as it was before
- Test 1: Is core.autocrlf set?
  - Run `git config --global core.autocrlf` locally, what does that return for you?
- Test 2: If core.autocrlf is set in the .gitattributes file, does that work?
  - Add a `.gitattributes` file with the following contents: `* text=auto`
  - Now make a change to the comment in the `spawn_redis_server.sh` file, run `git add .`, `git commit -m "test"` and `git push origin master` - does that work or does it complain like before?

**Comment by Jarak-Jakar** [comment]
> > While git typically normalises the endings to and from the Unix style for you when you check code out and commit it back, your code editor probably by default adds new lines with the Windows style.
> 
> @Jarak-Jakar Trying to dig a bit deeper - wouldn't we expect this to fix the problem? i.e. Even if users have windows-style endings in their local directory, when the git push happens, they'd get normalized to unix-style. (assuming it's configured properly)

It will indeed, _when they do a_ `git push`.  Which, of course, they probably haven't done when using the CLI tool to run a test.  So yes, I expect it'll only be an issue when working with the CLI tool to check correctness before making the git commit to complete the stage.

> Maybe adding a `.gitattributes` file to all the starter repos would fix this? Could you try the following please:
> 
>     * Keep your editor on the windows-style endings setting as it was before
> 
>     * Test 1: Is core.autocrlf set?
>       
>       * Run `git config --global core.autocrlf` locally, what does that return for you?

Running it with the `global` flag returns no output, but it apparently has an error exit code.  Running it _without_ the `global` flag inside the codecrafters-redis-python repo returns `true`.  I'm guessing I never set it globally (I remember having dealt with this back in the day, but I can't remember the context anymore).
 
>     * Test 2: If core.autocrlf is set in the .gitattributes file, does that work?
>       
>       * Add a `.gitattributes` file with the following contents: `* text=auto`
>       * Now make a change to the comment in the `spawn_redis_server.sh` file, run `git add .`, `git commit -m "test"` and `git push origin master` - does that work or does it complain like before?

Everything seemed to run OK after doing all that.  To double-check things, I also ran `codecrafters test` immediately afterwards, and everything ran fine then.  I then set the line endings in my editor (IntelliJ IDEA, currently) to CRLF (tricker than you might expect, IDEA seemed to keep resetting itself to LF) and modified the `spawn_redis_server.sh` file and ran it again.  Everything seemed to run fine.  Double-checking the line endings in Notepad++ seemed to confirm they were still set to Windows CRLF mode.  So, I'm not totally sure, but it does _look like_ using the `.gitattributes` file might well do the trick.

**Comment by rohitpaulk** [comment]
> Everything seemed to run OK after doing all that. To double-check things, I also ran codecrafters test immediately afterwards, and everything ran fine then. I then set the line endings in my editor (IntelliJ IDEA, currently) to CRLF (tricker than you might expect, IDEA seemed to keep resetting itself to LF) and modified the spawn_redis_server.sh file and ran it again. Everything seemed to run fine. Double-checking the line endings in Notepad++ seemed to confirm they were still set to Windows CRLF mode. So, I'm not totally sure, but it does look like using the .gitattributes file might well do the trick.

Ah, perfect! 

> It will indeed, when they do a git push. Which, of course, they probably haven't done when using the CLI tool to run a test. So yes, I expect it'll only be an issue when working with the CLI tool to check correctness before making the git commit to complete the stage.

The CLI tool does do a git commit + push under the hood: https://github.com/codecrafters-io/cli/blob/78860209746f8c23e75b2f55e92372b33a71ce6e/internal/commands/test.go#L96. It just pushes to a temp branch + doesn't rely on the git push output for logs (it uses a different log streaming mechanism that is faster & more flexible).

---

Okay, so looks like we have a plan - we'll add `.gitattributes` to all our our starter repos and I'll keep an eye out and see if others run into similar issues. Thanks so much for helping debug this @Jarak-Jakar!

I'll close this once `.gitattributes` are present on all repos.

**Comment by Jarak-Jakar** [comment]
> The CLI tool does do a git commit + push under the hood: [codecrafters-io/cli@`7886020`/internal/commands/test.go#L96](https://github.com/codecrafters-io/cli/blob/78860209746f8c23e75b2f55e92372b33a71ce6e/internal/commands/test.go#L96). It just pushes to a temp branch + doesn't rely on the git push output for logs (it uses a different log streaming mechanism that is faster & more flexible).

Huh.  In that case, I really don't understand where the issue was coming from.  Must be that my understanding of git is worse than I thought (which probably isn't that surprising, to be honest).  At least it looks like we've probably found a way to deal with this issue for everyone.

> I'll close this once .gitattributes are present on all repos.
👍

**Comment by rohitpaulk** [comment]
Okay - `.gitattributes` should be added everywhere now. Will keep an eye out for similar reports. Thanks for all the help @Jarak-Jakar!

**Pull request closed without merging**
